### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [odoomrp/odoomrp-utils#103]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] stock_picking_customer_ref
- [ ] stock_quants_shortcuts
- [ ] crm_lead_marketing_info
- [ ] purchase_order_line_form_button
- [ ] crm_claim_extra_ref
- [ ] product_category_in_header
- [ ] account_invoice_line_stock_move_info
- [ ] mrp_bom_line_search_view
- [ ] stock_disable_force_availability_button
- [ ] purchase_order_copy_bid_origin
- [ ] product_pricelist_partnerinfo
- [ ] product_stock_info
- [ ] l10n_eu_product_adr_report
- [ ] stock_picking_package_preparation_add_to_wave
- [ ] stock_quant_stock_info
- [ ] product_packaging_views
- [ ] mrp_show_related_attachment
- [ ] mrp_bom_structure_show_child
- [ ] mrp_production_unreserve_movements
- [ ] stock_move_partner_info
- [ ] mrp_stock_quant_shortcut
- [ ] stock_planning
- [ ] stock_warehouse_orderpoint_stock_info
- [ ] purchase_order_line_stock_available
- [ ] mrp_production_qty_to_produce_info
- [ ] stock_planning_procurement_generated_by_plan
- [ ] stock_planning_mrp
- [ ] stock_picking_carrier
- [ ] procurement_manager
- [ ] product_uom_change_fix
- [ ] stock_quant_reservation_status
- [ ] crm_claim_ref_search
- [ ] partner_group
- [ ] sale_stock_quant_shortcut
- [ ] delivery_partner_properties
- [ ] account_invoice_supplier_ref_required
- [ ] stock_picking_visible_scheduled_date
- [ ] purchase_pricelist_partnerinfo
- [ ] product_type
- [ ] stock_incoterm_extension
- [ ] account_invoice_line_wave_info
- [X] partner_address_type_default - https://github.com/odoomrp/odoomrp-utils/pull/125
- [ ] purchase_product_menu
- [X] mrp_stock_info - https://github.com/odoomrp/odoomrp-utils/pull/126
- [ ] analytic_production_cost_report
- [ ] sale_order_line_form_button
- [ ] stock_lot_note
- [ ] purchase_stock_quant_shortcut
- [ ] product_expiry_ext

**Comment by SodexisTeam** [comment]
We are porting partner_address_type_default to v9.

**Comment by anajuaristi** [comment]
Thank you!!
